---
# Monitoring role handlers

- name: restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: true

- name: restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted
    daemon_reload: true
