---
# OxiRS Fuseki handlers

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart oxirs-fuseki
  ansible.builtin.systemd:
    name: oxirs-fuseki
    state: restarted

- name: reload oxirs-fuseki
  ansible.builtin.systemd:
    name: oxirs-fuseki
    state: reloaded
